CC = clang
DBG = lldb

SRC = $(wildcard ext/*.c)
OBJ = $(SRC:src/%.c=build/%.o)
PREPROCESSED = $(SRC:ext/%.c=preprocessed/%.preprocessed.c)
.PHONY: all run test debug debug-test check clean

all: build/main $(PREPROCESSED)

build:
	mkdir -p build

preprocessed:
	mkdir -p preprocessed

build/%.o: ext/%.c | build
	$(CC) -Wall -Wextra -O0 -g -c $< -o $@

build/main: $(OBJ)
	$(CC) -o $@ $(OBJ)

run: build/main
	./build/main

debug: build/main
	$(DBG) ./build/main

check:
	@which $(CC)  > /dev/null && echo "SUCCESS: $(CC) found"  || echo "ERROR: $(CC) not found"
	@which $(DBG) > /dev/null && echo "SUCCESS: $(DBG) found" || echo "ERROR: $(DBG) not found"

clean:
	rm -rf build preprocessed

